<?php

namespace ShopBundle\Repository;

/**
 * MintsordersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MintsordersRepository extends \Doctrine\ORM\EntityRepository
{
}
