shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }
category:
    path: /category/{slug}
    defaults: { _controller: ShopBundle:Category:index }
products:
    path: /products/{slug}
    defaults: { _controller: ShopBundle:Products:index }